# Generated by Django 5.2.5 on 2025-08-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('important', models.BooleanField(default=False)),
                ('due_by', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
